version: 2
updates:
   - package-ecosystem: "terraform"
     directories:
      - "/"
      - "/dev"
     schedule:
      interval: "daily"
     open-pull-requests-limit: 10
     commit-message:
       prefix: "dep(terraform)"
     groups:
      terraform-deps:
        patterns:
          - "*"
     ignore:
      - dependency-name: "*joonvena/terraform-aiven-posgres*"
      - dependency-name: "git::ssh://git@github.com/joonvena/terraform-aiven-posgres.git?ref=main"
   - package-ecosystem: "github-actions"
     directories:
      - "/"
      - "/.github/actions/*"
     schedule:
       interval: "daily"
     open-pull-requests-limit: 2
     commit-message:
       prefix: "deps(actions)"
