version: 2
registries:
   github-joonvena:
      type: git
      url: https://github.com
      username: x-access-token
      password: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
updates:
   - package-ecosystem: "terraform"
     directories:
      - "/"
      - "/dev"
     schedule:
      interval: "daily"
     open-pull-requests-limit: 10
     registries: "*"
     commit-message:
       prefix: "dep(terraform)"
   - package-ecosystem: "github-actions"
     directories:
      - "/"
      - "/.github/actions/*"
     schedule:
       interval: "daily"
     open-pull-requests-limit: 2
     commit-message:
       prefix: "deps(actions)"
