version: 2
updates:
   - package-ecosystem: "terraform"
     directories:
      - "/"
      - "/dev"
     schedule:
      interval: "weekly"
     open-pull-requests-limit: 10
     commit-message:
       prefix: "deps(terraform)"
     groups:
      terraform-deps:
        patterns:
          - "*"
